### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by darkestkhan** [AdaCore/gsh#14]
Tried to build this shell accordingly to README description (on windows 10)

> Alternatively to just compile the gsh binary you can do:
> 
> $ gprbuild -p -P posix_shell

Here is shell output (blessed be emacs):

> c:\repos>git clone https://github.com/AdaCore/gsh.git
> git clone https://github.com/AdaCore/gsh.git
> Cloning into 'gsh'...
> Checking out files: 100% (1248/1248), done.
> 
> c:\repos>cd gsh
> cd gsh
> 
> c:\repos\gsh>gprbuild.exe -p -P posix_shell
> gprbuild.exe -p -P posix_shell
> object directory "C:\repos\gsh\obj\dev\" created
> object directory "C:\repos\gsh\lua\obj" created for project lua
> library directory "C:\repos\gsh\lua\lib" created for project lua
> object directory "C:\repos\gsh\os\obj\dev" created for project os
> library directory "C:\repos\gsh\os\lib" created for project os
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos strmatch.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos gsh_lexer.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos gsh.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos builtin.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos gsh_unit.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos gsh_dump_tree.adb
> gcc -c -g -O0 windows.c
> gcc -c -g -O0 windows-kernel.c
> gcc -c -g -O0 unix.c
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos os.ads
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos os-fs.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos os-fs-stat.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos os-fs-dir.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos os-exec.adb
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lzio.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lvm.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lundump.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL luac.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lua.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL ltm.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL ltablib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL ltable.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lstrlib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lstring.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lstate.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lparser.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL loslib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lopcodes.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lobject.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL loadlib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lmem.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lmathlib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL llex.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL liolib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL linit.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lgc.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lfunc.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL ldump.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL ldo.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL ldebug.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL ldblib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lctype.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lcorolib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lcode.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lbitlib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lbaselib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lauxlib.c
> gcc -c -Wall -O2 -DLUA_COMPAT_ALL lapi.c
> gcc -c -DHAVE_CONFIG_H -g -O0 xmalloc.c
> gcc -c -DHAVE_CONFIG_H -g -O0 xfree.c
> gcc -c -DHAVE_CONFIG_H -g -O0 vi_mode.c
> gcc -c -DHAVE_CONFIG_H -g -O0 util.c
> gcc -c -DHAVE_CONFIG_H -g -O0 undo.c
> gcc -c -DHAVE_CONFIG_H -g -O0 tilde.c
> gcc -c -DHAVE_CONFIG_H -g -O0 text.c
> gcc -c -DHAVE_CONFIG_H -g -O0 terminal.c
> gcc -c -DHAVE_CONFIG_H -g -O0 signals.c
> gcc -c -DHAVE_CONFIG_H -g -O0 shell.c
> gcc -c -DHAVE_CONFIG_H -g -O0 search.c
> gcc -c -DHAVE_CONFIG_H -g -O0 savestring.c
> gcc -c -DHAVE_CONFIG_H -g -O0 rltty.c
> gcc -c -DHAVE_CONFIG_H -g -O0 readline.c
> gcc -c -DHAVE_CONFIG_H -g -O0 parens.c
> gcc -c -DHAVE_CONFIG_H -g -O0 nls.c
> gcc -c -DHAVE_CONFIG_H -g -O0 misc.c
> gcc -c -DHAVE_CONFIG_H -g -O0 mbutil.c
> gcc -c -DHAVE_CONFIG_H -g -O0 macro.c
> gcc -c -DHAVE_CONFIG_H -g -O0 kill.c
> gcc -c -DHAVE_CONFIG_H -g -O0 keymaps.c
> gcc -c -DHAVE_CONFIG_H -g -O0 isearch.c
> gcc -c -DHAVE_CONFIG_H -g -O0 input.c
> gcc -c -DHAVE_CONFIG_H -g -O0 histsearch.c
> gcc -c -DHAVE_CONFIG_H -g -O0 history.c
> gcc -c -DHAVE_CONFIG_H -g -O0 histfile.c
> gcc -c -DHAVE_CONFIG_H -g -O0 histexpand.c
> gcc -c -DHAVE_CONFIG_H -g -O0 funmap.c
> gcc -c -DHAVE_CONFIG_H -g -O0 display.c
> gcc -c -DHAVE_CONFIG_H -g -O0 complete.c
> gcc -c -DHAVE_CONFIG_H -g -O0 compat.c
> gcc -c -DHAVE_CONFIG_H -g -O0 callback.c
> gcc -c -DHAVE_CONFIG_H -g -O0 bind.c
> gcc -c -DHAVE_CONFIG_H -g -O0 windows-termcap.c
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh.ads
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-re.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-tokens.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-tokens-lexer.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-traces.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-builtins.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-opts.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-parser.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-states.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-states-io.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-tree.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-tree-dumps.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-tree-evals.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-utils.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos lua.adb
> gcc -c -g -gnata -gnatwe -g -O0 -gnat12 -gnatwcfijklmopruvz -gnaty -fpreserve-control-flow -fdump-scos sh-lua_bindings.ads
> cannot generate code for file sh-lua_bindings.ads (package spec)
> gprbuild: *** compilation phase failed
> 

Seems like at least one package is missing.

**Comment by Nikokrock** [comment]
Indeed the makefile is generating one file needed for some test. Alternatively call before gprbuild:
python ./unit_test_gen. It will generate the missing unit

**Comment by darkestkhan** [comment]
Some comments: the required version of python is 2.x (at first I used 3.x which resulted in syntax error at line  94 - missing parenthesis).

In addition this scripts doesn't generate file - everything is printed to stdout (of course redirecting to src/sh-lua_bindings.adb fixes the problem).

Other than that gsh compiles. (but I do think that executables should be in Exec_Dir instead of Object_Dir).

Thanks for help

**Comment by Nikokrock** [comment]
Will update the README to reflect that. Usually I am using the makefile and thus call make install, but indeed Exec_Dir would be better
